const fieldNameMap = {
  fullNamePart1_1: "text_1qyai",
  fullNamePart1_2: "text_2mgvh",
  employerNoPart1: "text_3epkl",
  epfNoPart1: "text_4ynwa",
  otherNamesPart1_1: "text_5fzko",
  otherNamesPart1_2: "text_6vche",
  addressPart1: "text_7qotv",
  nationalityPart1: "text_8kgvf",
  sexPart1: "text_9vsi",
  agePart1: "text_10bksq",
  birthDayPart1: "text_11wfhl",
  placeOfBirthPart1: "text_12omja",
  marriedOrSinglePart1: "text_13jtci",
  spouseNamePart1_1: "text_14rval",
  spouseNamePart1_2: "text_15uqyr",
  nameAndBirthPlaceFatherPart1_1: "text_16goml",
  nameAndBirthPlaceFatherPart1_2: "text_17ktmg",
  motherNamePart1_1: "text_18mzrw",
  motherNamePart1_2: "text_19pzcb",
  nameAndBirthPlaceFatherFatherPart1_1: "text_20vemm",
  nameAndBirthPlaceFatherFatherPart1_2: "text_21hbwv",
  nameAndBirthPlaceMotherFatherPart1_1: "text_22zhvb",
  nameAndBirthPlaceMotherFatherPart1_2: "text_23octo",
  lastEmployerNameAddressPart1_1: "text_24ihff",
  lastEmployerNameAddressPart1_2: "text_25oitc",
  nicPart1: "text_26czaj",
  lastEmployment: "text_27fbnt",
  lastEmploymentPeriod: "text_28ckbs",
  employerNoPart2: "text_29cekz",
  epfNoPart2: "text_30lefa",
  fullNamePart2_1: "text_31lodh",
  fullNamePart2_2: "text_32vtfl",
  otherNamesPart2_1: "text_33zpdl",
  otherNamesPart2_2: "text_34ftg",
  addressPart2_1: "text_35pilx",
  addressPart2_2: "text_36ojff",
  nicPart2: "text_37iis",
  nominations0Part2Name: "text_39tjiv",
  nominations0Part2Nic: "text_44doyh",
  nominations0Part2Age: "text_49smnp",
  nominations0Part2Relationship: "text_54huti",
  nominations0Part2Share: "text_59ecrj",
  nominations1Part2Name: "text_40lpav",
  nominations1Part2Nic: "text_45gpc",
  nominations1Part2Age: "text_50kxcr",
  nominations1Part2Relationship: "text_55kltp",
  nominations1Part2Share: "text_60tmmo",
  nominations2Part2Name: "text_41cnjw",
  nominations2Part2Nic: "text_46bydp",
  nominations2Part2Age: "text_51dlpl",
  nominations2Part2Relationship: "text_56aipg",
  nominations2Part2Share: "text_61zklt",
  nominations3Part2Name: "text_42gqor",
  nominations3Part2Nic: "text_47csbx",
  nominations3Part2Age: "text_52oiyc",
  nominations3Part2Relationship: "text_57kbmi",
  nominations3Part2Share: "text_62zmsw",
  nominations4Part2Name: "text_43qusb",
  nominations4Part2Nic: "text_48mhdm",
  nominations4Part2Age: "text_53yvck",
  nominations4Part2Relationship: "text_58myqu",
  nominations4Part2Share: "text_63wobk",
  employerAndAddressPart2: "text_64udhq",
  employmentPart2: "text_65oujx",
  employedDatePart2: "text_66epko",
  grossSalaryPart2: "text_67utwa",
  datePart2: "text_68kkth",
  employerNoPart3: "text_69k",
  epfNoPart3: "text_70awom",
  fullNamePart3_1: "text_71stnb",
  fullNamePart3_2: "text_72ubdh",
  datePart3_1: "text_73cxnf",
  witnessNamePart3_1: "text_74sfnp",
  namePart3: "text_75ztmk",
  datePart3_2: "text_76fajj",
  witnessNamePart3_2: "text_77byhi",
  witnessPositionAndAddressPart3_1: "text_78vxfl",
  witnessPositionAndAddressPart3_2: "text_79lmux",
};

const fieldMaxLength = {
  fullNamePart1: 62,
  otherNamesPart1: 55,
  spouseNamePart1: 45,
  fatherNameAndBirthPlacePart1: 38,
  motherNamePart1: 38,
  fatherFatherNameAndBirthPlacePart1: 32,
  motherFatherNameAndBirthPlacePart1: 28,
  lastEmployerNameAddressPart1: 45,
  fullNamePart2: 36,
  otherNamesPart2: 36,
  addressPart2: 36,
  fullNamePart3: 48,
  witnessPositionAndAddressPart3: 62,
};

module.exports = {
  fieldNameMap,
  fieldMaxLength,
};
